default_language_version:
  python: python3.12

repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-added-large-files
            args: ['--maxkb=1024']
        -   id: check-merge-conflict

  -   repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.12.10
      hooks:
        -   id: ruff
            args: [--fix, --show-fixes]
        -   id: ruff-format

  -   repo: https://github.com/pre-commit/mirrors-clang-format
      rev: v20.1.8
      hooks:
        -   id: clang-format
            types_or: [c++, c, header]
